apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx_img
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        livenessProbe:
          exec:
            command:
            - pgrep
            - telegraf
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services_key    #key must be same in all services to share singtle IP 
spec:
  selector:
    app: nginx
  type: LoadBalancer
  # loadBalancerIP: 192.168.49.10
  ports:
    - name: http
      protocol: TCP
      port: 80        #Other Service access the nginx-service via 80
      targetPort: 80  #to which port, nginx-service should send request
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
