apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  # annotations: 
  #   metallb.universe.tf/allow-shared-ip: sharing-key #to get an address from the pool of
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  loadBalancerIP: 192.168.49.11
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin_img
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          # env:
          #   - name: PMA_HOST
          #     value: mysql-service
          #   - name: PMA_PORT
          #     value: "3306"
          #   - name: MYSQL_ROOT_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: mysql-secrets
          #         key: root-password